---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minecraft
  namespace: flux-system
spec:
  interval: 2h0m0s
  url: https://itzg.github.io/minecraft-server-charts/
