---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-k8s-gateway
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/xorcat/k8s_gateway
  ref:
    branch: make-zonefile-roll
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts/
