---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: gitlab
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      hosts:
        domain: "${SECRET_INTERNAL_DOMAIN}"
        https: true
        gitlab:
          name: "git.${SECRET_INTERNAL_DOMAIN}"
          https: true
        minio:
          name: "minio.git.${SECRET_INTERNAL_DOMAIN}"
          https: true
        ssh: "git.${SECRET_INTERNAL_DOMAIN}"
        kas:
          name: "kas.git.${SECRET_INTERNAL_DOMAIN}"
          https: true
      ingress:
        configureCertmanager: false
        class: traefik
        provider: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
    gitlab:
      webservice:
        ingress:
          tls:
            secretName: gitlab-tls
      gitlab-runner:
        runners:
          config: |
            [[runners]]
              executor = "kubernetes"
              environment = [ "container=kube" ]
    certmanager:
      install: false
    nginx:
      install: false
    nginx-ingress:
      enabled: false
    minio:
      ingress:
        tls:
          secretName: gitlab-minio-tls
    kas:
      ingress:
        tls:
          secretName: gitlab-kas-tls
    registry:
      enabled: false
