---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
