---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - secret.sops.yaml
spec:
  postBuild:
    substituteFrom:
      - kind: secret
        name: external-dns-cloud-credentials
