# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hSs5+f6lMg==,iv:KqKoDGspz0wbC/4up9LlzLx4usylulAnv6klo1VaXF4=,tag:uJ4bsRrCp+NSmHzu7ijBXA==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:M+xx+EzuQx3vJand/dzV,iv:CM5T4cMGowdYz+ZIEuDGT6N0VRw9Xt0QfKpp0LDNY0w=,tag:RVXtSJHONXNJOTMcDJntbA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:XuU1c1X0mEmbpw==,iv:ItyqkNpqaDf/8jpZ9EZdg6xd9Z/6hxozoiv4LK/zX5k=,tag:I63Uuw27DGkeZxkO6aOw5Q==,type:str]
    SECRET_GRAFANA_PASS: ENC[AES256_GCM,data:xuqMocJ7Qf3Ai6NbNk/esal9yItHqvFoMyXr7VfqhAXm,iv:SRbdStF4sS4b1sjo5KiurEjhcaJVvvC26hTdPTg7wb0=,tag:PRZ3YxZbLantvJsr6tQrHA==,type:str]
    SECRET_TM_PASS: ENC[AES256_GCM,data:zX9ZslUKLguxcp3SIXrYeXg0uZT1bTtPvtFsdKUybzlxhHo5SbZTcQ==,iv:i+ZjrJJYz1leyNHZ/DWE8JyWYpMZXZCjqZrw/yyOaYs=,tag:bfE/DReFg0C/1+nlJKQhCQ==,type:str]
    SECRET_MEDIA_PASS: ENC[AES256_GCM,data:iDbKOgSRAhPXLc9lUPxebFd/SbSLYb8Bh+ercKSJhnyvHp0b,iv:0g3JrvA9aNJoaziwixaKZAHGPny/J28gGjrMkgiJ8GE=,tag:/2/JDFvfKTxY4N4W5Tysmw==,type:str]
    SECRET_UNIFI_INFLUX_PASS: ENC[AES256_GCM,data:mXYLu2lkapY0aoTj5GMy+ZPjwGAiTOUquhVz3/CBSYz5PA2XAwhA,iv:gUDI94KGBdfUJtqm8ARw5p+vc3Xd2T0atBPzfdwBsDA=,tag:Ba6iJoETQvAUvuIijrqTiQ==,type:str]
    SECRET_UNIFI_READONLY_PASS: ENC[AES256_GCM,data:ggiOcWYS+Xv3/t5laHz5ntYd92cFWMXpnQwwLkvxTp51uvw=,iv:/7idy1TQ9rf32W8CybUyHizogpJSxKRjdzfn5jQzziU=,tag:An878VcnF0BaV3BWd5gZBw==,type:str]
    SECRET_HASSDB_PASSWORD: ENC[AES256_GCM,data:iBDfqZva7Xd9dZ5/88pYAzYUxkptf+2TaoAkixDPUtlapjqIqOw=,iv:RlMgsJpRMCr7Dqpp1LIp+EJYPREp9aEv1o92IaGtLww=,tag:wQt8t52B29vHLh8UfmMm8Q==,type:str]
    SECRET_HARBOR_PASSWORD: ENC[AES256_GCM,data:7FgCsz1rDB98Bl1goe0e1Fw=,iv:2GLB0r0y1GQ9s3MkQsSrSGYOujPVCv/crQvYrWJilVM=,tag:5lc7kpByIRyNnTgvWnnr2A==,type:str]
    SECRET_HARBOR_CRYPT_KEY: ENC[AES256_GCM,data:mvk/DF+jHpVDWOGo/Ale3g==,iv:xugL33JT3+jDpAQoE9z5jtMbs0JhhCDAWWgKuvogXjM=,tag:Iv+7F7FnmrtB+0Tm/RK9Pg==,type:str]
    SECRET_MAPSAPI_ISSUER: ENC[AES256_GCM,data:srIFOF0DzmeCzw==,iv:qqmKAmzTPQbNFh7gKirHwOBcrkLFx77ec8vgppQkP58=,tag:japhOD1uhIEOci9dnt2tIA==,type:str]
    SECRET_MAPSAPI_KEY_ID: ENC[AES256_GCM,data:dt+GG7VbI72q0w==,iv:YKBCAHvR7B1K5UIGoG19o9G6ee4g7EWjn7S/BidAjCI=,tag:lgsNQjJCxEiX+wUYLQpG7g==,type:str]
    SECRET_SLACK_APITOKEN: ENC[AES256_GCM,data:zWftH1xAwzH9Sio2GfPNhqx5IhnVhPA67wFfEoV2tV6M4xz5BJ6DSB+u16zIiYrIAi98/MMCcMZiteJocYjRPPzAKOXcvf0qRGuegw==,iv:wTHF4+jM06Dv1SfWF0rfiuN1XbfA6XUm4GO861yhkHY=,tag:GWPKsjJUd07ApU8riGIBNA==,type:str]
    SECRET_AUTH_CREDS: ENC[AES256_GCM,data:67SWlKrUOjy4+T/JmA+N0j1TfcOpW0M6MZsVQHWQGIRAnY2NxBQFm/2H8rbkpjStsDnI00JwA8L/qC//V5UMUnf4T1jqEBsh+lestA==,iv:arE8uQ2ZU6o2eglWbbV8l19+kl37NUafUK1UlK9AGoM=,tag:sGZ5Y93EBqx85vSDfo7P7A==,type:str]
    SECRET_PHOTOPRISM_PASS: ENC[AES256_GCM,data:c0n9gYX6ebL+c7DNd1Ju0U/ORAkFxvLFXkKI5JLWfNUfIBWnSFEXkVhtNG1/MA==,iv:dVq7B3zJ+1nTb+02T3Dxi30oZTeal3hYNe7vVlEQKlo=,tag:Sa0DT219L5iVV/0IeaSnjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZDEzb2J0cml2SWZjaW5S
            MlBPamUzNDIyS2srcmk2OXN5YkhJSVRZQkhzCmdCZWNsb2JyTWlRNnVhaVg3RzNs
            L0ljcXhnRGdwazkvUzBCK2JLRDM5ZEUKLS0tIHdYNUdER2pZQmphNTRyeXZGVDdK
            ajJvZmt1Vmp2OWhQN0MwbWtPWHI2QUEKi95x5iqmJJ6ar/Wn26JK6pt72x4zgOug
            dJ0rZVd0VEPNDv/HrHpe4T9DmATPkKyg1IABr+z2mHeQLJhMbWOdtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-28T10:46:25Z"
    mac: ENC[AES256_GCM,data:g6DGpybDUZM2FSKdhdqjEhSWTFytPYysao7tFcbehR5/KSUefpi+zWrFXOJoXRADrFIHZP9uCA2BYb7COKIB0siLrfcXOBcJG2mFC4fxL742L9n9OPcn/1v9morQrhthv1ckcgh/a7bxIXCm0Yq17joQEc3N9c/yNx+88cNny4Q=,iv:IDfRN7+CH4Edu0CQBNjdCT4Jo6lf/QlVkCDLj+CGtw0=,tag:rW+kL65/VgVhdnpCCpF0xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
