# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mixyCp4FGA==,iv:aXqMY936EfskE6mXcSy6o0L2iuJtRMGJbpX7eBFjBuM=,tag:nRSwtGfiR9gi0JZAUokORg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:WC0me/uft27FUA==,iv:p3N4jGyE1xNbM1daNrajwD2JCbkSeWHjR4hUaAEX8hM=,tag:qlT8IhepcuBabuPq27y8AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcTNKdWV5YmczSmVxMjFI
            L2lkUkttOHJkZXN4OXNIOG5yT1lqMyttK1N3CnplSy9od21mUnZxTGxpUkN6OVpp
            TWdqelp5WE0xVzJ4UnliL3k4NnhXNXcKLS0tIEcvSWdMV2QrZ2ppd3A3SFpoVTFa
            KzYzM3haYmh2UUcyY3VUc3NHdkliSUkKH3s0+7ZOuR51n6dmoBT5eec7laPHjnUs
            kDOmueSbn3REIJMIoVTwsHdsNWAgSjZEAGeSekqLdc1GueiW3Rjuyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T05:38:49Z"
    mac: ENC[AES256_GCM,data:YLvkNwZUAxwp5+NaBgvgBEGgUKA95LWSDTA6yMmDcvjAyAg7zRb7/pPgsTfh0uyh37sZNdfaKg3opGf/kgZU2baXy77FaA78fxVxEP33h9e4UpQRkwTN8hTaeURZoYMrZtyNm2I0mmACC7Z1c/bkH2Ihwy8083MsIUSg6ZVLZMk=,iv:YshHPakb3Dw7j8NOWfmmC3LN/PT7hNQPo2FHuNS7MWQ=,tag:5Z7+JgtL/z7j2cLJnjPQgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
