# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2SIksWMMaQ==,iv:bKRyHyvpa8Ei/nvjjOAbL5sdllY+Fd+wZVLYEEa0IYU=,tag:mLhCyVE64iC6DyS3SQFACg==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:4qgg8z9uAgTUgyo21qIz,iv:/9DNcOqXplG7B2ehVnd41pwS1487J0UZq7u7gqynO8c=,tag:RjO4fjI5CYeL2skj4LfNnA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:rMoBnl/BqsuPaQ==,iv:rpHhmntIram7gbKsrHI5lmvGwt+pkCDQpCh1xtJ1BGk=,tag:XWWTXlhy3ETOIClXwoRZIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUWhGcHhrcGxqTmRka3Vk
            V2ZlTFFMeGFKbWE0TDNGL1Z3WnZLM2ptT253CmJHNkU5ZzNEVDVKdy9YbE9PTFpQ
            Wkpod2VSTjUrbXB6RXF4YWxMYk42Q3MKLS0tIGFuQ2lDVUZCbUNpV2Evclp5dTAv
            NjdNancvRHAwUzBPTlc4RmVqc1prZUUK3+7jUqKg32RjsI/xSTppkKlqqbR3yDwI
            NUYYUtMpaf7+rP8ZN0Hh2X4JVZwtRZDqGRDs0zgCM094HcnGJFByWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-15T00:20:09Z"
    mac: ENC[AES256_GCM,data:AyE0QgmwKoToGANvmXcYwwNscowpq5Y/3V2nwFvE6LciqlbNVTiDE/chozu1+4t1H6wvINrG/KkFyLPyQ0YPCWL/hRgrkRpsoetF5wcLV8pgYrjWn8QJ+McXReWxlVAQ5YDX3y9DA1eOc9Sp/ppGhxrDBLwGjqYM+VITCuQR/I4=,iv:vHfBVllBhB7cGtbNNXsjMq0Q3AqBzSkof1scY/WKsT0=,tag:wVVUBdJfcxy/edVAP9r4UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
