# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ludQho+ugg==,iv:ZD7DkLCl3x9/K2+hFBsY/XoJ+Eh61YHZjBhl6ljdV40=,tag:qqxeqNRsCz70E05TrcnLgA==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:Kqv2TMdOTO/5HPzq97Kz,iv:aVpGpqRCyYhWD6qsF5Motaoib7yfWbWR0EycRQWa6zs=,tag:yR0P2u/52R3RT5t8WSfExw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:ob7MtPKQntHLHA==,iv:LTA8vJ4dT1TM6BdJ7nYW/ezwUE7EfTHkUz0ULUelOps=,tag:ijWxAqjn22XHYjbQTKj2+w==,type:str]
    SECRET_GRAFANA_PASS: ENC[AES256_GCM,data:HxhpnxzyIuEysrTsXdJQ9NJliJ2MKPz/DnSxJgDD4fyD,iv:P2RFqZIVCmfz+pBZua7US1iWUhXOu1OVAiL9O5eXDow=,tag:7kLjbMfZ6z1XdrtydOZoCQ==,type:str]
    SECRET_TM_PASS: ENC[AES256_GCM,data:Dv/WbZxQGxLj5h9PMkRy+LzrFvfjhNpGPFkKLZTuGIo/zIISVEqZQg==,iv:Q2kitQtFFNPk5dhakAKMWZmSt4Z2oDkj6RV94idDAuE=,tag:O/v1d/d0ibKivqAFDUgwnA==,type:str]
    SECRET_MEDIA_PASS: ENC[AES256_GCM,data:3//74ipPfIQVz6DUbm3rYFauLst+Ut66pSNj2+t6F2w6Re+L,iv:wk3+vhIvM49mXsJELhZYM/4FxzFZsCwF6JrSso//XZY=,tag:gOWUR6GSzAIDmwe19GTJpA==,type:str]
    SECRET_UNIFI_INFLUX_PASS: ENC[AES256_GCM,data:NSE2pUKMh1kEtgUndTm6Bmjruw4rwIjGO+EE0zlkUkk8bvNFdU5J,iv:7XmPB6TuFh/olO+pIjFFNu5ZdpqLA3w295JwQG4MJsI=,tag:PByw1sKQgJ3TgSMZDs7Wgw==,type:str]
    SECRET_UNIFI_READONLY_PASS: ENC[AES256_GCM,data:WqsG5aTsll4R6QTAFP49SoIximdtol1vrClgAkVF2hejqRE=,iv:YGMpMaRBadl+rvlE4ZAv6DwafYXUceeZqcjTbn0LP3c=,tag:PFtqFc5HNGrpGGPkBeQ/AQ==,type:str]
    SECRET_HASSDB_PASSWORD: ENC[AES256_GCM,data:3XkWBTp7zQAdBsptqsdE/o9gVUPoWEtQ9gl22ckrC3/K+GzY6Nw=,iv:1NokilrSIb1vhQhEwrhWEr71P+dtcpOCGel2NKmORf8=,tag:Pet19toN9mb2lCXS4KM/UQ==,type:str]
    SECRET_HARBOR_PASSWORD: ENC[AES256_GCM,data:3+9gy+pTtU74ZxV4vxv0HPo=,iv:4mS07iaEtU4tmNJ2+FuH3EQ2Uj+gMnNJLXIxuvH+V6M=,tag:l2OTPGOkscV1ev/hvK3O+g==,type:str]
    SECRET_HARBOR_CRYPT_KEY: ENC[AES256_GCM,data:eDlUnwQDVhXFH1A4/IFY6A==,iv:Cs/8ZQVMaDpweKgb73ctHwgbM8dudEHReOOIbRYIaeQ=,tag:NtS0JzdpgolVCA7gVniR2Q==,type:str]
    SECRET_MAPSAPI_ISSUER: ENC[AES256_GCM,data:psrW8/BCChGKuQ==,iv:FRWXCLH1R8wfLrBO2X/DcmUhcuCanfIpDNxSCzQW3bU=,tag:gGUsy7Zwrm9OYxthgHr/ow==,type:str]
    SECRET_MAPSAPI_KEY_ID: ENC[AES256_GCM,data:FTMENRnfdcCqsw==,iv:QRWMgsFMpiWnnYhcmdiMeXCUXOcwX/O638LNgVW1DhE=,tag:PG7XOixkoIbuBA3aG0CVTA==,type:str]
    SECRET_SLACK_APITOKEN: ENC[AES256_GCM,data:n/CIKtiK+izjDCUF4PPjkE6lOSg2aodLBspJpWnLg40N7cU5jBZHucVPneBEUP65kRgixkowBPU1yFhLpfn3gkPkvsV5sQIX5WkDmQ==,iv:C5nRtU7/k231N1yn+NmTr9o7/cZ8wfNud/A7ONgECQc=,tag:Di1HpY1sgUocs/ntGopnDQ==,type:str]
    SECRET_AUTH_CREDS: ENC[AES256_GCM,data:jetUdsSv3mrQodytuC+Y/805KMyabxG/R4ZowwYgKb4S5XWxSUNBLLuYwxIil5MNfPuXANgovsonQchthQo6v5Sn+eGlcJOIxZ7dEA==,iv:eYYp0LWZlLNxfgR2zuQlZhvhg+45jnEuRNxTRa7ER8U=,tag:jCpY//uYNqG0af0Y44APgA==,type:str]
    SECRET_PHOTOPRISM_PASS: ENC[AES256_GCM,data:kIuVjoStbkRGrgl6Ixe0h88pnB5pRKxONjV8/xE3v3R+u5ryGih6PbX3GqgWIQ==,iv:qd/SXxQuX/L0FcmYARYkXVJHzmbaG/s4gjtA7GkM8Lk=,tag:sPJ/7GuhAW37mF2jneufnw==,type:str]
    SECRET_PHOTOPRISM_DB: ENC[AES256_GCM,data:PIxee6JrUCQ2jTb1yqeYj/cv5/jb1kT2mMmIE7Zwyin6GZ8Z,iv:szpZbi+i8ziijZTJxBHeft48Lex3KlqMqpMKdGvB18Y=,tag:uubJS5uRWEdChxVg3xQpSA==,type:str]
    SECRET_PHOTOPRISM_DB_ROOT: ENC[AES256_GCM,data:rdfrpCc5QkFejroUfXHIA6+XIkTGJ46U4OzMuqNeGP6wwCxQrAY6J5BTzcyK/w==,iv:mCSbkDOIXyXu1qhPqXsl/4Pom0jY8a9Oy45InRcMUqc=,tag:xhfzxjWNWcOuplkb1F53tg==,type:str]
    SECRET_VPN_PVK: ENC[AES256_GCM,data:ef5sW59KeRS09tlbtzjV53N40e8vR4+KHwqaxfTsn+UkNZgjx6NLxT/XQ1U=,iv:cPYjKtmsgHozGG7B8wAU8J6yS23sziVSpvJyJ61SCbA=,tag:sOWkMAeP4b3B7cW93mBUxg==,type:str]
    SECRET_VPN_CONFIG: ENC[AES256_GCM,data:L39PH6lUAe/zJN83K+y1Z6b6SKvRi4QAACtIhjxs8Y+qg5ydgroWR7Sot28AjPP3M8IF1RlEpsdcPeBmSuqp7YCgXUJjGcSfXHp/ZGGNIUtgKyUoU9YeR3DtANMKWMZlDs0GaJO2uszk0WBaqA3ANsQIPxvvR/T6+o1SAoboV2f/uL9PPKJT1DjE+b0TB4sWEXcPx6NOaZt4m6UTJOEm5qm3o7FBYDzXngy3EIg0xafCYWpfbIuAsYT6H1RkdCMELI0fIKg4gGk7ZFc8RhfRKTDAjkTtqpfQd6kVnt40r23IhlGktkxKZWZwpeHgTeGKr09JaJt1v+V4a253B/HcwuV7LGQ+BPOMkgo=,iv:r+VQeXEQO/mdCS/qFV7bTiMXrNASs8fpLqpwb6kiB1Q=,tag:fRJ6oYxYQ2BnoE8WY2NqXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb1U0VGc5YUQwNzhaTDhB
            VzN4dDlLMmpkMWtzbnlKZVhDRTlpV1lkNVdnCnkyNUUvVHkvQ25kYTdEVWxScXNy
            M2R4Rk1vUmVYWGg3TTU0Q0c1R0ZaMEUKLS0tIGRPQzBLdGVxRXVUQnlabmVrVDhx
            UkJJR3BQUlgxckVUZktOK05iRVlHMmMK5uPN+hTuv4FQlrVuvjICouC3M94jBRUV
            ZLB3exHjHi/emZuqK3IMVwtdEJvDjWlDO6LySN8Xp8Qm55XSMo9IvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-29T12:42:14Z"
    mac: ENC[AES256_GCM,data:bE5lGqydHyXwyAUHck5v1dsEz4qj1OhWPoicLgZ7lc4P6qeftT1sjSvH2jGdoHFYxJN/wIEy+M2DzZv56iCXJDmsKgtAShS9lMSaKkJanf4Qc0vJXwNceD+t+jC7VXKBWX7YmZQN/hVjzakK68ys2fHtogxP+kb2R5H3ImhKsMc=,iv:GXflalNlqTXNGQ7bT7N0EBYKgznhy8Gcv8wNPhLjPds=,tag:gvRwXF+89at7g35QlLARfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
