---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - common.yaml
  - operator.yaml
  # - cluster.yaml
  # - storageclass-fast.yaml
  # - storageclass-slow.yaml
