---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.9.3
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    expose:
      type: ingress
      tls:
        certSource: secret
        secret:
          secretName: harbor-core-tls
          notarySecretName: harbor-notary-tls
      ingress:
        hosts:
          core: "harbor.${SECRET_INTERNAL_DOMAIN}"
          notary: "sign.harbor.${SECRET_INTERNAL_DOMAIN}"
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
    externalURL: "https://harbor.${SECRET_INTERNAL_DOMAIN}"
