---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: goldilocks
      version: 6.3.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:
    vpa:
      enabled: true
      recommender:
        extraArgs:
          prometheus-address: |
            http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
          storage: prometheus
    dashboard:
      enabled: true
      replicaCount: 2
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-auth-local@kubernetescrd"
        hosts:
          - host: "gold.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - "gold.${SECRET_INTERNAL_DOMAIN}"
            secretName: gold-tls
