---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mapsapi-test
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: "harbor.${SECRET_INTERNAL_DOMAIN}/work/mapsapi-test"
      tag: v0.1.4
    imagePullSecrets:
      - name: harbor
    env:
      - name: MAPSAPI_JWT_ISSUER_ID
        value: "${SECRET_MAPSAPI_ISSUER}"
      - name: MAPSAPI_JWT_KEY_ID
        value: "${SECRET_MAPSAPI_KEY_ID}"
      - name: MAPSAPI_JWT_KEY
        value: /secrets/es256.key
      - name: MAPSAPI_ORIGIN
        value: "mapsapi-test.${SECRET_INTERNAL_DOMAIN}"
    persistence:
      config:
        enabled: true
        type: secret
        name: mapsapi-signing-key
        mountPath: /secrets
        readOnly: true
    service:
      main:
        ports:
          http:
            port: &port 8000
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      startup:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: *port
          failureThreshold: 30
          periodSeconds: 10
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "mapstest-tls"
    # # FIXME: Uncomment this block to ensure multiple
    # # replicas of the pod are scheduled on different nodes
    # topologySpreadConstraints:
    #   - maxSkew: 1
    #     topologyKey: kubernetes.io/hostname
    #     whenUnsatisfiable: DoNotSchedule
    #     labelSelector:
    #       matchLabels:
    #         app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
