apiVersion: v1
kind: Secret
metadata:
    name: mapsapi-signing-key
    namespace: default
type: Opaque
data:
    es256.key: ENC[AES256_GCM,data:RI9hbLoLN4LUeTarrkOm+03S+Hgkb5efdmbbjLJOgsvsMSoxZrEYAK5+H5JjuqVSyQBTjYsI/f45sN1cxm5lieaRU6yU3nIjf+5/PZRezpo83j5Qk2JUdf+S+GnOCq05ZSyPYCBPykKfUI39AcA9eq1nMkohY1LBpD+ISUt9lBiQ0d0FphZ3ftUYWNwBMW/6TaZSdojSdPaQApN2HY/CuP9Dnzu4C0mFiF9c8jActx6UGPNUxOKh2SPvChhYhtpue7qmO5JXxgowR7lUH67ta7Ji4nxb0YnssPlaEtu4StvrFOBR5m5b2ud0cb6YP/SvvWvhj5OkjIEDPIUQ0fsR09ytdnRpcoVOCAP5Q6hdtC4jSGj9BO8nTdjsLCYoKTlpk+R99sUWSnXXnpap1mLW82XiVi+4Ia3QngIMzHPmp748vnrXq83G8djVF5Al1PyT7pRFIzScEsM=,iv:sfzKGxmT6hhFHjv2aDbBdL9J0LKNVC9c12WT6VTEgpc=,tag:siPcS6LORsjbTUt+3S7aGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbHlYZlVSQkZ5ODVHS1c0
            clB3MWdtUUxZK0ZMSnpiaklpVlZ3L0dBcUZRCmNjTk5sNVFxTFVVY2lDS1N1YkhB
            NUZZZVJCZ1NYaUxybHNmbHl6K3A5N00KLS0tIDNVYnNtUFpsUGRjeWVUWlU0aUNW
            YzlNaXBzZ0xGSTJZUTBQUkQ5Z0I1T1EKyptIkt1kRmPKofHp+0jp60a22M3RdZUB
            jYE2o6VzWJmKnyuGbY3hy4bRb+gQZYzasUzZKDyYVFCDPO4FsjsMIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T06:47:37Z"
    mac: ENC[AES256_GCM,data:836OiW4fKT+Txl9eOfK96X/DE/7hSq15qreRDnzwl4DcN3wuHaVbsJXbfiydoS7SFCUX+0CH+axdovNJNVq5Hj+wqq6kljp51ne6kduWMd6v4iWa9DjkijyrqBFA0dF0Ea2ZTMZFW9/kDiTUNwZ3cZlAAaO49IshOE4Hg2kM+V8=,iv:vi5izXl49ciTVY2703MegshsQVRECuCdCUvu1BVs8l4=,tag:a21vG0Jo4wuo+85uMXtkCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
