---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '>=4.0.16'
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nfs:
      server: "${NFS_SERVER}"
      path: "${NFS_PATH}"
      mountOptions:
        - nfsvers=3
    replicaCount: 1
