# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-cloud-credentials
  namespace: cert-manager
data:
  credentials.json: ${BOOTSTRAP_GCP_SA}
stringData:
  GCP_PROJECT: ${BOOTSTRAP_GCP_PROJECT}
