# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloud-credentials
  namespace: networking
data:
  credentials.json: ${BOOTSTRAP_GCP_SA}
stringData:
  GCP_PROJECT: ${BOOTSTRAP_GCP_PROJECT}
