---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    # renovate: depName=traefik/traefik-helm-chart datasource=github-tags
    tag: v20.8.0
  url: https://github.com/traefik/traefik-helm-chart.git
  ignore: |
    /*
    !/traefik/crds/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./traefik/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: traefik-crds
