---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: github-ips
  namespace: networking
spec:
  # https://api.github.com/meta
  # curl -s https://api.github.com/meta | jq '.hooks[]' -r | sed 's/^/ - /g'
  ipWhiteList:
    sourceRange:
      - 192.30.252.0/22
      - 185.199.108.0/22
      - 140.82.112.0/20
      - 143.55.64.0/20
      - 2a0a:a440::/29
      - 2606:50c0::/32
      # include rfc1918 ranges since traefik chains do not support OR operations
      # https://github.com/traefik/traefik/issues/6007
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: github-only
  namespace: networking
spec:
  chain:
    middlewares:
      - name: github-ips
