---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-plex
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: kube-plex
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.27.2.5929-a806c5905
    kubePlex:
      image:
        repository: ghcr.io/ressu/kube-plex
        tag: latest

    # Override this with the plex claim token from plex.tv/claim
    claimToken: ""

    # Set the timezone of the plex server
    timezone: Australia/Brisbane

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "home.${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/hostname: "plex.${SECRET_DOMAIN}."
      hosts:
        - "plex.${SECRET_DOMAIN}"
        - "plex.${SECRET_INTERNAL_DOMAIN}"
      tls:
        - hosts:
            - "plex.${SECRET_DOMAIN}"
            - "plex.${SECRET_INTERNAL_DOMAIN}"
          secretName: "plex-pub-tls"
    persistence:
      transcode:
        enabled: true
        storageClass: media-fs
        size: 50Gi
      data:
        claimName: media
        accessMode: ReadWriteMany
      config:
        storageClass: media-fs
        accessMode: ReadWriteOnce
        size: 50Gi
