---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex.yaml
  - photos.yaml
  - prowlarr.yaml
  - sab.yaml
  - sab2.yaml
  - radarr.yaml
  - sonarr.yaml
  - overseerr.yaml
  - tautulli.yaml
