---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex.yaml
  - photos.yaml
  - prowlarr.yaml
  - sab.yaml
  - sab2.yaml
  - radarr.yaml
  - sonarr.yaml
  - radarr-uhd.yaml
  - sonarr-uhd.yaml
  - overseerr.yaml
  - tautulli.yaml
  - recyclarr-cron.yaml
  - recyclarruhd-cron.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: recyclarr
    namespace: media
    files:
      - recyclarr-config.yaml
  - name: recyclarruhd
    namespace: media
    files:
      - recyclarruhd-config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
