---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-plex
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: kube-plex
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.28.0.5999-97678ded3
    kubePlex:
      enabled: false
      image:
        repository: ghcr.io/ressu/kube-plex
        tag: latest

    # Override this with the plex claim token from plex.tv/claim
    claimToken: ""

    # Set the timezone of the plex server
    timezone: Australia/Brisbane

    resources:
      requests:
        cpu: 1400m

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        # traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "home.${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/hostname: "plex.${SECRET_DOMAIN}."
      hosts:
        - "plex.${SECRET_DOMAIN}"
        - "plex.${SECRET_INTERNAL_DOMAIN}"
      tls:
        - hosts:
            - "plex.${SECRET_DOMAIN}"
            - "plex.${SECRET_INTERNAL_DOMAIN}"
          secretName: "plex-pub-tls"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - sabnzbd
                      - sabnzbd2
              topologyKey: kubernetes.io/hostname
            weight: 100
    persistence:
      transcode:
        enabled: true
        storageClass: media-fs
        size: 50Gi
      data:
        claimName: media
        accessMode: ReadOnlyMany
        subPath: media
      config:
        accessMode: ReadWriteOnce
        size: 50Gi
