---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-plex
      version: 0.3.7
      sourceRef:
        kind: HelmRepository
        name: kube-plex
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.28.0.5999-97678ded3
    kubePlex:
      enabled: false
      image:
        repository: ghcr.io/ressu/kube-plex
        tag: latest

    # Override this with the plex claim token from plex.tv/claim
    claimToken: ""

    # Set the timezone of the plex server
    timezone: Australia/Brisbane

    probes:
      # Liveness probe configuration
      liveness:
        # Enable the liveness probe
        enabled: true
        # Set custom to `true` if you wish to specify your own liveness probe
        custom: true
        # The spec field contains the values for the default livenessProbe.
        # If you selected `custom: true`, the spec field holds the definition of the livenessProbe.
        spec:
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /identity
            port: 32400

      # Redainess probe configuration
      readiness:
        # Enable the readiness probe
        enabled: true
        # Set custom to `true` if you wish to specify your own readiness probe
        custom: true
        # The spec field contains the values for the default readinessProbe.
        # If you selected `custom: true`, this field holds the definition of the readinessProbe.
        spec:
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /identity
            port: 32400

      # Startup probe configuration
      startup:
        # Enable the startup probe
        enabled: true
        # Set custom to `true` if you wish to specify your own startup probe
        custom: false
        # The spec field contains the values for the default startupProbe.
        # If you selected `custom: true`, this field holds the definition of the startupProbe.
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 30

    resources:
      requests:
        cpu: 1400m

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        # traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "home.${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/hostname: "plex.${SECRET_DOMAIN}."
      hosts:
        - "plex.${SECRET_DOMAIN}"
        - "plex.${SECRET_INTERNAL_DOMAIN}"
      tls:
        - hosts:
            - "plex.${SECRET_DOMAIN}"
            - "plex.${SECRET_INTERNAL_DOMAIN}"
          secretName: "plex-pub-tls"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - sabnzbd
                      - sabnzbd2
              topologyKey: kubernetes.io/hostname
            weight: 100
    persistence:
      transcode:
        enabled: true
        storageClass: media-fs
        size: 50Gi
      data:
        claimName: media
        accessMode: ReadOnlyMany
        subPath: media
      config:
        claimName: plexmigrate-radarr-config
