---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v3.3.1
    env:
      TZ: "Australia/Brisbane"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-auth-local@kubernetescrd"
        hosts:
          - host: "sab.arr.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sab.arr.${SECRET_INTERNAL_DOMAIN}"
            secretName: sab-tls
    persistence:
      config:
        enabled: true
        storageClass: block
        size: 30Gi
        accessMode: ReadWriteOnce
        annotations:
          helm.sh/resource-policy: "keep"
      media:
        enabled: true
        existingClaim: media
    resources:
      requests:
        memory: 2Gi
        cpu: 300Mi
      limits:
        memory: 2Gi
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
