apiVersion: v1
data:
    RADARR_APIKEY: ENC[AES256_GCM,data:0Jlb61L0eSj+tuQCi3fc/fI81isSiSF8MPyBj6hOYEForSzCYpxmAuULjW4=,iv:bEDybHdu1yIMK2TflCQO/R6a3eA/MuhkFRdz9BTxWB8=,tag:JjMjKAKAy4ZmSKi1M1lanQ==,type:str]
    SONARR_APIKEY: ENC[AES256_GCM,data:3YyJBSZLaQ+4agsNGLI7upXxrUvlFAxGjCXi31LBMoR0VTjdB4/7GILV8cY=,iv:J+6CBiEKbcQVH3ZG23+pyDIn+kctJ63++jjtdhA6bVQ=,tag:AADccNuYYoH7PKL9qfmmAw==,type:str]
kind: Secret
metadata:
    name: recyclarr
    namespace: media
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVTVqWWVEY1NRRmdGVTkv
            dXlpNzVoa1pwZDQzbXNQeVZENy9GUHpaSEI4Ck1pYkFrdnVJZEN4dThNRnNkUlRj
            NDh2OTJuUDlnL3hkQkdDWDVJYVpBUUkKLS0tIDF5WXl0M3R1SXp6M25KbE9ML1FO
            NnU1dU5zWUZCVEJvVzEySjJyaDdVWU0Kz+seJZWFIumQ6tlJTL2Q1tbQ1/uP5siv
            TBmw041zuSOk1wNakPibOTT1tG6T74CQEDo2mfJdhOsO7nlnhz/WFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T23:46:10Z"
    mac: ENC[AES256_GCM,data:d45WgEC0P4k1x56z0MAndskC9jRbG2FtuiK/8jqJ8SGDlKVlAoF/o8GCMEHJY1BZ3peRsHlnsbFwFHNWb21VaM7DJusC5vB1xFqF0kLNn3VLxwnfXtZ94ltJWzdEAD3TF92REbSPMw2V9ivdwYaf5s7fIIquoVN+iDAQyw09kWw=,iv:BJAbYLYH40sMn+m/pPkWZWVj/G8bwUTppbs8MFKF4N4=,tag:h6Wfo8lHR02RK0IHVk68iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
