---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.8.1507
    env:
      TZ: "Australia/Brisbane"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "son.arr.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "son.arr.${SECRET_INTERNAL_DOMAIN}"
            secretName: sonarr-tls
    persistence:
      config:
        enabled: true
        storageClass: block
        size: 5Gi
        accessMode: ReadWriteOnce
        annotations:
          helm.sh/resource-policy: "keep"
      media:
        enabled: true
        existingClaim: media
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2s
        labels:
          app.kubernetes.io/component: monitoring
