---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: media
spec:
  chart:
    spec:
      chart: kah-common-chart
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 1.2.2
      interval: 5m
  interval: 5m
  values:
    global:
      nameOverride: tautulli
    env:
      TZ: "Australia/Brisbane"
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.10.2
    service:
      main:
        ports:
          http:
            port: 8181
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        ingressClassName: traefik
        hosts:
          - host: &host mon.arr.${SECRET_INTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tautulli-tls
    persistence:
      config:
        enabled: true
        storageClass: block
        size: 5Gi
        accessMode: ReadWriteOnce
        annotations:
          helm.sh/resource-policy: "keep"
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 500Mi
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2s
        labels:
          app.kubernetes.io/component: monitoring
