---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.7.6
    env:
      TZ: "Australia/Brisbane"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 200m
        memory: 3000Mi
    postgresql:
      enabled: true
      image:
        repository: postgres
        tag: "14.4"
      postgresqlUsername: postgres
      postgresqlDatabase: "${SECRET_HASSDB_PASSWORD}"
      postgresqlDataDir: "/data/pgdata"
      persistence:
        enabled: true
        existingClaim: homeassistant-db
        mountPath: "/data/"
      shmVolume:
        enabled: false
      volumePermissions:
        enabled: false
