---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Service
metadata:
  name: media-udp
  namespace: media
  labels:
    app: media
  annotations:
    coredns.io/hostname: "media.${SECRET_INTERNAL_DOMAIN}"
    metallb.universe.tf/allow-shared-ip: "media-share-service"
spec:
  ports:
    - port: 137
      name: udp137
      protocol: UDP
    - port: 138
      name: udp138
      protocol: UDP
  type: LoadBalancer
  selector:
    app: media
---
apiVersion: v1
kind: Service
metadata:
  name: media-tcp
  namespace: media
  labels:
    app: media
  annotations:
    coredns.io/hostname: "media.${SECRET_INTERNAL_DOMAIN}"
    metallb.universe.tf/allow-shared-ip: "media-share-service"
spec:
  ports:
    - port: 139
      name: tcp139
    - port: 445
      name: tcp445
  type: LoadBalancer
  selector:
    app: media
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: media
  namespace: media
spec:
  serviceName: media-udp
  replicas: 1 # Never go > 1!
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      hostNetwork: false # otherwise the auto-discovery does not work
      containers:
        - name: media
          image: mbentley/timemachine:smb
          securityContext:
            privileged: true
          ports:
            - containerPort: 137
              name: udp137
              protocol: UDP
            - containerPort: 138
              name: udp138
              protocol: UDP
            - containerPort: 139
              name: tcp139
            - containerPort: 445
              name: tcp445
          volumeMounts:
            - name: media
              mountPath: /opt/timemachine
            - name: var-lib-samba
              mountPath: /var/lib/samba
            - name: var-cache-samba
              mountPath: /var/cache/samba
            - name: run-samba
              mountPath: /run/samba
          env:
            - name: ADVERTISED_HOSTNAME
              value: ""
            - name: CUSTOM_SMB_CONF
              value: "false"
            - name: CUSTOM_USER
              value: "false"
            - name: DEBUG_LEVEL
              value: "1"
            # - name: MIMIC_MODEL
            #   value: "TimeCapsule8,119"
            - name: EXTERNAL_CONF
              value: ""
            - name: HIDE_SHARES
              value: "no"
            - name: TM_USERNAME
              value: "x"
            - name: TM_GROUPNAME
              value: "x"
            - name: TM_UID
              value: "1000"
            - name: TM_GID
              value: "1000"
            - name: PASSWORD
              value: "${SECRET_MEDIA_PASS}"
            - name: SET_PERMISSIONS
              value: "false"
            - name: SHARE_NAME
              value: "TimeMachine"
            - name: SMB_INHERIT_PERMISSIONS
              value: "no"
            - name: SMB_NFS_ACES
              value: "yes"
            - name: SMB_METADATA
              value: "stream"
            - name: SMB_PORT
              value: "445"
            - name: SMB_VFS_OBJECTS
              value: "acl_xattr streams_xattr"
            - name: VOLUME_SIZE_LIMIT
              value: "0"
            - name: WORKGROUP
              value: "WORKGROUP"
      volumes:
        - name: var-lib-samba
          emptyDir: {}
        - name: var-cache-samba
          emptyDir: {}
        - name: run-samba
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: media
      spec:
        storageClassName: media-fs
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 6Ti
