# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SwWqsHEMfHSdCRthmiGBhpmB9RO1oiEQ19Mg4P8C2e1INU2CUT1PuQ==,iv:FF5wuhJUhYN89GHypdWWnPBW0143fm44J7ysFjXN4As=,tag:efCxZJmPstdgLeRDfg4HMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1srmk6clsnj5dxvkn2emh84522cr47kr76xmplvuzddq5qxh5scusq92lzn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcWJDTWV6Q05KMWFZSC9Y
            VjdBYkR1QlR5WmVTNVNGZ2pPZDJHU3VJckh3CitzK0hleUVxWTkxUmkvK1duSzNq
            MzFNNTYyYW1FWTdUUTdhblVTUFJDbDgKLS0tIFNabzIzYTlncmMvVzlob1BNR290
            cnd5aXF0T05jTTBwbnRYb21TUFkwY28KEFOCNFY3BhfWk3NcPnljfKMXeWN/NLMU
            Qfv1WlwePTxGvqSTg3jfSaDAd2vJHX7O24hppVkqfG8wMA4iSgAI+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T14:19:09Z"
    mac: ENC[AES256_GCM,data:ClzQJrXeX0GOMQQPTWX+A0xbTZm2eoZHFGNKUtExUgqtwkdkokE/Yb9/K44gUW+Uo81OnMWwWwlTtqswHJg8YBuHtZCkoA2TJSc83Zoydd9DPrOFyG57HFq8GgPMcfyrrp51nBqTwy6WUg4gODvK8/8a/ZrwvGGmYQdi8PHPhsE=,iv:uY9OaOaSoCXxsy/hzN7VOZBtThxyvzwkpv7t0lzIL28=,tag:HuJEdJCHof+E5o9wSmjrxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
