---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.12.13
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: NotIn
                  values:
                    - slow-node
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          release: prometheus-stack
    installCRDs: false
    webhook:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53
      - --dns01-recursive-nameservers-only
    replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "8.8.8.8"
        - "8.8.4.4"
