apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - letsencrypt-production.yaml
  - letsencrypt-staging.yaml
  - secret.sops.yaml
spec:
  postBuild:
    substituteFrom:
      - kind: secret
        name: cert-manager-cloud-credentials
