---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudDNS:
            project: "${GCP_PROJECT}"
            serviceAccountSecretRef:
              name: cert-manager-cloud-credentials
              key: credentials.json
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
