---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-gateway
      version: 1.1.15
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
      interval: 5m
      reconcileStrategy: Revision
  values:
    fullnameOverride: k8s-gateway
    watchedResources:
      - Ingress
      - Service
    domain: ${SECRET_DOMAIN}
    fallthrough:
      enabled: true
      zones:
        - ${SECRET_DOMAIN}
    ttl: 60
    zoneFile:
      filename: ${SECRET_DOMAIN}.db
      contents: |
        ${SECRET_INTERNAL_DOMAIN}.          3600 IN SOA  k8sgw.${SECRET_INTERNAL_DOMAIN}. security.${SECRET_DOMAIN}. 1 86400 7200 4000000 11200
        kubeapi.${SECRET_INTERNAL_DOMAIN}.  3600 IN A    ${KUBE_VIP_ADDR}
        k8sgw.${SECRET_INTERNAL_DOMAIN}.    3600 IN A    ${METALLB_K8S_GATEWAY_ADDR}
        nas.${SECRET_INTERNAL_DOMAIN}.      3600 IN A    10.1.1.15
        home.${SECRET_INTERNAL_DOMAIN}.     3600 IN A    10.1.1.104
        printer.${SECRET_INTERNAL_DOMAIN}.  3600 IN A    10.1.1.108
    service:
      type: LoadBalancer
      port: 53
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${METALLB_K8S_GATEWAY_ADDR}"
      externalTrafficPolicy: Local
        # Increase replicaCount and set an anti-affinity if you wish to scale this
    replicaCount: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - k8s-gateway
              topologyKey: kubernetes.io/hostname
